#!/bin/bash
for skimmer in `tr '\n' ' ' < reference`; do
#	echo "Analysing" ${skimmer}
	./skimlist -q -f rbnfiles/20200701.csv -t ${skimmer} > result.tmp
	grep deviation result.tmp 
done
rm -f result.tmp rbnfiles/*.zip
