#!/bin/bash
# Get yesterday's RBN data and run a number of analyses on it
# Put result in files rbnskew.txt, rbnskew2.txt, rbnskewr.txt,
# rbnhist.txt, rbnact.txt, and rbnref.txt and upload them to web host.
# Checks if it has already run for today and if it has, exits
#set -x

# Move to correct folder to allow cron execution on RPi
[ -d "/home/pi/rbnskew" ] && cd /home/pi/rbnskew

DATE=`date -u --date="1 days ago" +%Y%m%d`
OLDESTRES=`date -u --date="5 days ago" +%Y%m%d`.txt
FOLDER="webserver"

echo "---"
echo "Job started "`date -u "+%F %T" `
START=$SECONDS

# Check if we already did the work for today, if so, exit
[ -f $FOLDER/done ] || echo "Never" > $FOLDER/done
if [ "$DATE" == "`cat $FOLDER/done`" ]; then
    echo "Nothing to do."
    exit
fi

[ -f $FOLDER/$OLDESTRES ] || ./initweb

# Do the work
echo "Downloading RBN data for "`date -u --date="1 days ago" +%Y-%m-%d`

wget --quiet --no-hsts http://www.reversebeacon.net/raw_data/dl.php?f=$DATE -O $FOLDER/rbndata.zip

FILESIZE=$(stat -c%s $FOLDER/rbndata.zip)
if [[ $FILESIZE != "0" ]]; then
    gunzip < $FOLDER/rbndata.zip > $FOLDER/rbndata.csv
    echo "Downloaded yesterday's "$((`wc -l < $FOLDER/rbndata.csv` - 2))" spots into rbndata.csv"
	./makenewref
    ./$FOLDER/updatewebdata
    ./$FOLDER/updatehistdata
    ./$FOLDER/updateactdata
    cd $FOLDER
    ./upload
    echo "-"
    echo "Uploaded to web hosting"
    echo $DATE > done
else
    echo "Could not download yesterday's RBN data!"
    echo "Job failed "`date -u "+%F %T" `
    exit
fi
echo "Job ended "`date -u "+%F %T"`" and took $((SECONDS-START)) seconds"
exit
