#!/bin/bash
# Get yesterday's RBN data and run a full analysis on it
FOLDER="rbnfiles"
FILE=`date --date="1 days ago" +%Y%m%d`
mkdir -p $FOLDER
wget --quiet --no-hsts http://www.reversebeacon.net/raw_data/dl.php?f=$FILE -O $FOLDER/$FILE.zip
FILESIZE=$(stat -c%s "$FOLDER/$FILE.zip")
if [[ $FILESIZE != "0" ]]; then
    gunzip < $FOLDER/$FILE.zip > $FOLDER/$FILE.csv
    echo "Downloaded yesterday's "$((`wc -l < $FOLDER/$FILE.csv` - 2))" spots into "$FOLDER/$FILE.csv"."
    rm -f $FOLDER/$FILE.zip
    ./rbnskew -q -f $FOLDER/$FILE.csv -s > $FILE.txt
    echo "Stored analysis result in "$FILE.txt"."
else
    echo "Could not download yesterday's RBN data."
fi
exit
