#!/bin/bash
# Get yesterday's RBN data and run a full analysis on it
[ -d "/home/pi/rbnskew" ] && cd /home/pi/rbnskew
FILE=`date -u --date="1 days ago" +%Y%m%d`
FOLDER="webserver"
echo "---"
echo "Job started "`date -u "+%F %T" `
echo "Downloading RBN data for "`date -u --date="1 days ago" +%Y-%m-%d`
wget --quiet --no-hsts http://www.reversebeacon.net/raw_data/dl.php?f=$FILE -O $FOLDER/rbndata.zip
FILESIZE=$(stat -c%s $FOLDER/rbndata.zip)
if [[ $FILESIZE != "0" ]]; then
    gunzip < $FOLDER/rbndata.zip > $FOLDER/rbndata.csv
    echo "Downloaded yesterday's "$((`wc -l < $FOLDER/rbndata.csv` - 2))" spots into rbndata.csv"
    ./rbnskew -wq -f $FOLDER/rbndata.csv | sed "/processing/c\ " | grep -v "accuracy an" > $FOLDER/rbnskew.txt
    echo "Updated web data in rbnskew.txt"
    ./rbnskew -wqh -f $FOLDER/rbndata.csv | sed "/processing/c\ " | grep -v "accuracy an" > $FOLDER/rbnskew2.txt
    echo "Updated web data in rbnskew2.txt"
#    ./rbnskew -wqr -f $FOLDER/rbndata.csv | sed "/processing/c\ " | grep -v "accuracy an" > $FOLDER/rbnskewr.txt
#    echo "Updated web data in rbnskewr.txt"
    cd $FOLDER
	./upload
    echo "Uploaded to web hosting"
else
    echo "Could not download yesterday's RBN data!"
fi
echo "Job ended "`date -u "+%F %T" `
exit
