#!/bin/bash
# Analyses the content of webserver/rbndata.csv and
# creates summaries of station and skimmer activity
# per continent and band.
# Result is saved in rbnact.txt
#set -x

echo "-"

FOLDER="webserver"
DATE=`date -u --date="1 days ago" +%Y-%m-%d`

echo "Updating activity data for:" $DATE

./cunique -f $FOLDER/rbndata.csv > $FOLDER/rbnact.txt
echo "Last updated "`date -u "+%F %T"`" UTC" >> $FOLDER/rbnact.txt

exit
