#!/bin/bash
# Use yesterday's RBN data in rbndata.csv and check all the current 
# reference skimmers against each other
# Assumes webserver/rbndata.csv has already been downloaded
#set -x

DATADATE=`date -u --date="1 days ago" +%Y-%m-%d`
FOLDER="webserver"

echo "-"
#echo "Job started "`date -u "+%F %T"`
echo "Reference skimmer integrity analysis."

FILESIZE=$(stat -c%s $FOLDER/rbndata.csv)

if [[ $FILESIZE != "0" ]]; then
	echo "Based on "$((`wc -l < $FOLDER/rbndata.csv` - 2))" RBN spots from "$DATADATE"." > $FOLDER/rbnref.txt
	echo >> $FOLDER/rbnref.txt
    SKIMMERS=`cat reference | sort | grep -v '#' | tr '\n' ' '`
    echo "Skimmers: " $SKIMMERS
	echo "  Skimmer   [ppm]  Spots    Adjustment " >> $FOLDER/rbnref.txt
	echo "  -------------------------------------" >> $FOLDER/rbnref.txt
    for skimmer in $SKIMMERS; do
         # echo "Analyzing skimmer" $skimmer "with file" $FOLDER/rbnref.csv
        ./rbnskew -q -f $FOLDER/rbnref.csv -t $skimmer > $FOLDER/result.tmp
        RESULT=`grep "#" $FOLDER/result.tmp`
        if [[ $RESULT != "" ]]; then
            echo "$RESULT" | tr "#" " " >> $FOLDER/rbnref.txt
        else
            echo "Skimmer" $skimmer " - no spots" >> $FOLDER/rbnref.txt
        fi
    done
	echo >> $FOLDER/rbnref.txt
	echo "Last updated "`date -u "+%F %T"`" UTC" >> $FOLDER/rbnref.txt
    echo "Updated web data in rbnref.txt"
else
    echo "Could not access webserver/rbndata.csv!"
fi
exit
