#!/bin/bash
# Download yesterday's RBN data and check all the current 
# reference skimmers against eachother
#set -x
# Move to correct folder to allow cron execution on RPi
[ -d "/home/pi/rbnskew" ] && cd /home/pi/rbnskew

FILE=`date -u --date="1 days ago" +%Y%m%d`
DATADATE=`date -u --date="1 days ago" +%Y-%m-%d`
FOLDER="webserver"

echo "---"
echo "Job started "`date -u "+%F %T"`
echo "Reference skimmer integrity analysis."
echo "Downloading RBN data for "`date -u --date="1 days ago" +%Y-%m-%d`

wget --quiet --no-hsts http://www.reversebeacon.net/raw_data/dl.php?f=$FILE -O $FOLDER/rbnref.zip

FILESIZE=$(stat -c%s $FOLDER/rbnref.zip)

if [[ $FILESIZE != "0" ]]; then
    gunzip < $FOLDER/rbnref.zip > $FOLDER/rbnref.csv
    echo "Downloaded yesterday's "$((`wc -l < $FOLDER/rbnref.csv` - 2))" spots into rbnref.csv" 
	echo "Based on "$((`wc -l < $FOLDER/rbnref.csv` - 2))" RBN spots from "$DATADATE"." > $FOLDER/rbnref.txt
	echo >> $FOLDER/rbnref.txt
    SKIMMERS=`grep -v '#' reference | tr '\n' ' '`
    echo "Skimmers: " $SKIMMERS
    # echo "Analysis based on file "$FOLDER"/rbnref.csv with" `wc -l < $FOLDER/rbnref.csv` "lines."
	echo "  Skimmer   [ppm]  Spots    Adjustment " >> $FOLDER/rbnref.txt
	echo "  -------------------------------------" >> $FOLDER/rbnref.txt
    for skimmer in $SKIMMERS; do
         # echo "Analyzing skimmer" $skimmer "with file" $FOLDER/rbnref.csv
        ./rbnskew -q -f $FOLDER/rbnref.csv -t $skimmer > $FOLDER/result.tmp
        RESULT=`grep "#" $FOLDER/result.tmp`
        if [[ $RESULT != "" ]]; then
            echo "$RESULT" | tr "#" " " >> $FOLDER/rbnref.txt
        else
            echo "Skimmer" $skimmer " - no spots" >> $FOLDER/rbnref.txt
        fi
    done
	echo >> $FOLDER/rbnref.txt
	echo "Last updated "`date -u "+%F %T"`" UTC" >> $FOLDER/rbnref.txt
    echo "Updated web data in rbnref.txt"
    cd $FOLDER
	./upload
    echo "Uploaded to web hosting"
else
    echo "Could not download yesterday's RBN data!"
fi
echo "Job ended "`date -u "+%F %T" `
exit
